title: BarberShop
description: "A blog for CTF writeups and notes I may find interesting"
author:
  name: "saintbarber"
  email: "saintbarb3r@gmail.com"
  url: "saintbarber.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "saintbarber"
year : "2020"
